package appaSystem.com.view;

import appaSystem.com.db.Conexao;
import appaSystem.com.db.DadosConexao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmInicio extends javax.swing.JFrame {

    Conexao con = new Conexao();
    DadosConexao dcon = new DadosConexao();
    
    DefaultTableModel lista = new DefaultTableModel();
    
    public void montaLista(){
        
        this.lista.setColumnCount(0);
        this.lista.setRowCount(0);
        
        jTable1.setModel(this.lista);
        
        con.conecta(dcon.getUrl(), dcon.getDriver(), dcon.getUsuario(), dcon.getSenha());
        String sql = "SELECT * FROM CONTATO";
        
        if(!txtPesquisar.getText().equals("")){
            
            sql +=" WHERE UPPER(NOME) LIKE '%"+txtPesquisar.getText().toUpperCase()+"%'"
                    +" OR TEL LIKE '%"+txtPesquisar.getText()+"%'";
            
        }
        
        sql += " ORDER BY NOME";
        
        con.executeConsulta(sql);
            
        lista.addColumn("Código");
        lista.addColumn("Nome");
        lista.addColumn("Telefone");

        try{
            while(con.rs.next()){
                lista.addRow(new String[]{
                    con.rs.getString("COD"),
                    con.rs.getString("NOME"),
                    con.rs.getString("TEL")
                });
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados para exibir na tabela!\n"+ex);
        }
        
        con.desconecta();
        jTable1.setModel(lista);

        
        
    }
    
    public void selecao(){
        
        int linha = jTable1.getSelectedRow();
        
        txtCodigo.setText(jTable1.getValueAt(linha, 0).toString());
        txtNome.setText(jTable1.getValueAt(linha, 1).toString());
        txtTelefone.setText(jTable1.getValueAt(linha, 2).toString());
        
        
    }
    
    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        montaLista();
        //colocar a janela no meio da tela
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnEditarNome = new javax.swing.JButton();
        btnCancelaNome = new javax.swing.JButton();
        btnSalvarNome = new javax.swing.JButton();
        btnEditarTelefone = new javax.swing.JButton();
        btnCancelarTelefone = new javax.swing.JButton();
        btnSalvarTelefone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Pesquisar");

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Telefone:");

        txtCodigo.setEnabled(false);

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtTelefone.setEnabled(false);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditarNome.setText("Editar");
        btnEditarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarNomeActionPerformed(evt);
            }
        });

        btnCancelaNome.setText("Cancelar");
        btnCancelaNome.setEnabled(false);
        btnCancelaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaNomeActionPerformed(evt);
            }
        });

        btnSalvarNome.setText("Salvar");
        btnSalvarNome.setEnabled(false);
        btnSalvarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNomeActionPerformed(evt);
            }
        });

        btnEditarTelefone.setText("Editar");
        btnEditarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTelefoneActionPerformed(evt);
            }
        });

        btnCancelarTelefone.setText("Cancelar");
        btnCancelarTelefone.setEnabled(false);
        btnCancelarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTelefoneActionPerformed(evt);
            }
        });

        btnSalvarTelefone.setText("Salvar");
        btnSalvarTelefone.setEnabled(false);
        btnSalvarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(24, 24, 24)
                                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEditarTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancelarTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSalvarTelefone))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnEditarNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCancelaNome)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSalvarNome))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCadastrar)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnEditarNome)
                    .addComponent(btnCancelaNome)
                    .addComponent(btnSalvarNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditarTelefone)
                        .addComponent(btnCancelarTelefone)
                        .addComponent(btnSalvarTelefone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        frmCadastrar form = new frmCadastrar();
        form.setVisible(true);
        
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        montaLista();
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        
        selecao();
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selecao();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSalvarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNomeActionPerformed
        
        con.conecta(dcon.getUrl(), dcon.getDriver(), dcon.getUsuario(), dcon.getSenha());
        String sql = "UPDATE CONTATO SET NOME = '"+txtNome.getText().trim()+"' WHERE COD = "+txtCodigo.getText();
        con.executeAtualizacao(sql);
        con.desconecta();
        
        txtNome.setEnabled(false);
        btnEditarNome.setEnabled(true);
        btnSalvarNome.setEnabled(false);
        btnCancelaNome.setEnabled(false);
        
        montaLista();
        
    }//GEN-LAST:event_btnSalvarNomeActionPerformed

    private void btnSalvarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTelefoneActionPerformed
        con.conecta(dcon.getUrl(), dcon.getDriver(), dcon.getUsuario(), dcon.getSenha());
        String sql = "UPDATE CONTATO SET TELEFONE = '"+txtTelefone.getText().trim()+"' WHERE COD = "+txtCodigo.getText();
        con.executeAtualizacao(sql);
        con.desconecta();
        
        txtTelefone.setEnabled(false);
        btnEditarTelefone.setEnabled(true);
        btnSalvarTelefone.setEnabled(false);
        btnCancelarTelefone.setEnabled(false);
        
        montaLista();
    }//GEN-LAST:event_btnSalvarTelefoneActionPerformed

    private void btnCancelarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTelefoneActionPerformed
        
        txtTelefone.setEnabled(false);
        btnEditarTelefone.setEnabled(true);
        btnSalvarTelefone.setEnabled(false);
        btnCancelarTelefone.setEnabled(false);
        montaLista();
    }//GEN-LAST:event_btnCancelarTelefoneActionPerformed

    private void btnCancelaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaNomeActionPerformed
        
        txtNome.setEnabled(false);
        btnEditarNome.setEnabled(true);
        btnSalvarNome.setEnabled(false);
        btnCancelaNome.setEnabled(false);
        
        montaLista();
    }//GEN-LAST:event_btnCancelaNomeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("Lista Telefônica");
    }//GEN-LAST:event_formWindowOpened

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        con.conecta(dcon.getUrl(), dcon.getDriver(), dcon.getUsuario(), dcon.getSenha());
        String sql = "SELECT NOME FROM CONTATO WHERE COD = "+txtCodigo.getText();
        
        con.executeConsulta(sql);
        
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente eliminar o registro "+sql+"?");
        
        if(resp == JOptionPane.YES_OPTION){
            sql = "DELETE FROM CONTATO WHERE COD = "+txtCodigo.getText();
            
            con.executeAtualizacao(sql);
            con.desconecta();
        
            txtNome.setEnabled(false);
            btnEditarNome.setEnabled(true);
            btnSalvarNome.setEnabled(false);
            btnCancelaNome.setEnabled(false);
            
            txtPesquisar.setText("");
            txtCodigo.setText("");
            txtNome.setText("");
            txtTelefone.setText("");
        
            montaLista();
            
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNomeActionPerformed
        
        txtNome.setEnabled(true);
        btnEditarNome.setEnabled(false);
        btnCancelaNome.setEnabled(true);
        btnSalvarNome.setEnabled(true);
        
    }//GEN-LAST:event_btnEditarNomeActionPerformed

    private void btnEditarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTelefoneActionPerformed
        
        txtTelefone.setEnabled(true);
        btnEditarTelefone.setEnabled(false);
        btnCancelarTelefone.setEnabled(true);
        btnSalvarTelefone.setEnabled(true);
    }//GEN-LAST:event_btnEditarTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelaNome;
    private javax.swing.JButton btnCancelarTelefone;
    private javax.swing.JButton btnEditarNome;
    private javax.swing.JButton btnEditarTelefone;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvarNome;
    private javax.swing.JButton btnSalvarTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
