/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appaSystem.com.view;

import appaSystem.com.controller.pedido.PedidoController;
import appaSystem.com.db.Conexao;
import appaSystem.com.db.DadosConexao;
import appaSystem.com.kernel.Acao;
import appaSystem.com.model.Pedido.Pedido;
import appaSystem.com.model.Pedido.PedidoPosicao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prince
 */
public class frmListaPedidos extends javax.swing.JFrame {

    Conexao con = new Conexao();
    DadosConexao dcon = new DadosConexao();
    PedidoPosicao pp;
    
    DefaultTableModel lista = new DefaultTableModel();
    int selecao;
    int selecaoId;
    
    public void montaLista(){
        
        this.lista.setColumnCount(0);
        this.lista.setRowCount(0);
        
        jTable1.setModel(this.lista);
        
        PedidoController pc = new PedidoController(0);
        List<Pedido> pedidos = new ArrayList<>();
        
        if(!txtProcurar.getText().equals("")){
            String sql = " UPPER(NOME_CLIENTE) LIKE '%"+txtProcurar.getText().toUpperCase()+"%'";
            pedidos = pc.consulta(sql);
        }else{
            pedidos = pc.consulta("");
        }
        
        lista.addColumn("ID");
        lista.addColumn("Nome do Cliente");
        lista.addColumn("Valor Total");
        lista.addColumn("Qtde de itens");
        lista.addColumn("Posição");

        for (Pedido pedido : pedidos) {
            
            lista.addRow(new String[]{
                String.valueOf(pedido.getId()),
                pedido.getNomeCliente(),
                String.valueOf(pedido.getValorTotal()),
                String.valueOf(pedido.getQtdeItens()),
                pedido.getPedidoPosicao().name()
            });
        }
        
        jTable1.setModel(lista);
        
    }
    
    public void selecao(){
        
        int linha = jTable1.getSelectedRow();
        
        String selecaoStr = this.lista.getValueAt(linha, 0).toString();
        String selecaoPos = this.lista.getValueAt(linha, 4).toString();
        this.selecao = Integer.parseInt(selecaoStr);
        
        if(selecaoPos.equals(PedidoPosicao.ABERTO.name())){
            this.pp = PedidoPosicao.ABERTO;
        }else if(selecaoPos.equals(PedidoPosicao.LIBERADO.name())){
            this.pp = PedidoPosicao.LIBERADO;
        }else{
            this.pp = PedidoPosicao.CANCELADO;
        }
        
    }
    /**
     * Creates new form frmListaPedidos
     */
    public frmListaPedidos() {
        initComponents();
        this.setTitle("Lista de Pedidos");
        montaLista();
        //colocar a janela no meio da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtProcurar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Procurar");

        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });
        txtProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProcurarKeyReleased(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLiberar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(btnLiberar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcurarActionPerformed

    private void txtProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcurarKeyReleased
        montaLista();
    }//GEN-LAST:event_txtProcurarKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        selecao();
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selecao();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "Selecione um pedido para ser alterado!");
        }else{
            if(pp.equals(PedidoPosicao.ABERTO)){

                this.setVisible(false);

                frmCadastroPedido form = new frmCadastroPedido(this.selecao,Acao.ALTERACAO);
                form.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Não é possível alterar um pedido que esteja com a posição\n"
                        + "Cancelado ou Liberado!");
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.setVisible(false);

        frmCadastroPedido form = new frmCadastroPedido(0,Acao.INCLUSAO);
        form.setVisible(true);
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int resp = -999;
        
        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "É necessário escolher um pedido para ser excluído");
        }else{
            resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja exluir o pedido número "+this.selecao+"?");
        }
        if(resp != -999){
            if(resp == JOptionPane.YES_OPTION){
                
                if(pp.equals(PedidoPosicao.LIBERADO)){
                    JOptionPane.showMessageDialog(null, "O pedido está Liberado! É possível apenas cancelar.");
                }else{
                 
                    PedidoController pc = new PedidoController(this.selecao);
                    pc.excluir(this.selecao);
                    
                    this.selecao = 0;
                    
                    montaLista();
                    
                }
            }
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        
        int resp = -999;
        
        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "É necessário escolher um pedido para ser Liberado");
        }else{
            resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja liberar o pedido número "+this.selecao+"?");
        }
        if(resp != -999){
            if(resp == JOptionPane.YES_OPTION){
                
                if(pp.equals(PedidoPosicao.LIBERADO)){
                    JOptionPane.showMessageDialog(null, "O pedido já está Liberado! É possível apenas cancelar.");
                }else if(pp.equals(PedidoPosicao.CANCELADO)){
                    JOptionPane.showMessageDialog(null, "O pedido está Cancelado!");
                }else{
                 
                    PedidoController pc = new PedidoController(this.selecao);
                    pc.liberar();
                    
                    this.selecao = 0;
                    
                    montaLista();
                    
                }
            }
        }
        
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        int resp = -999;
        
        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "É necessário escolher um pedido para ser Cancelado");
        }else{
            resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar o pedido número "+this.selecao+"?");
        }
        if(resp != -999){
            if(resp == JOptionPane.YES_OPTION){
                 
                PedidoController pc = new PedidoController(this.selecao);
                pc.cancelar();

                this.selecao = 0;

                montaLista();
            }
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
