/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appaSystem.com.view;

import appaSystem.com.controller.pedido.PedidoController;
import appaSystem.com.controller.pedido.PedidoItemController;
import appaSystem.com.db.Conexao;
import appaSystem.com.db.DadosConexao;
import appaSystem.com.kernel.Acao;
import appaSystem.com.model.Pedido.Pedido;
import appaSystem.com.model.Pedido.PedidoItem;
import appaSystem.com.model.Pedido.PedidoPosicao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prince
 */
public class frmPrincipal extends javax.swing.JFrame {
Conexao con = new Conexao();
    DadosConexao dcon = new DadosConexao();
    PedidoPosicao pp;
    
    DefaultTableModel lista = new DefaultTableModel();
    int selecao;
    int selecaoId;
    
    public void montaLista(){
        
        this.lista.setColumnCount(0);
        this.lista.setRowCount(0);
        
        jTable1.setModel(this.lista);
        
        PedidoController pc = new PedidoController(0);
        List<Pedido> pedidos = new ArrayList<>();
        
        if(!txtProcurar.getText().equals("")){
            String sql = " UPPER(NOME_CLIENTE) LIKE '%"+txtProcurar.getText().toUpperCase()+"%'";
            pedidos = pc.consulta(sql);
        }else{
            pedidos = pc.consulta("");
        }
        
        lista.addColumn("ID");
        lista.addColumn("Nome do Cliente");
        lista.addColumn("Valor Total");
        lista.addColumn("Qtde de itens");
        lista.addColumn("Posição");

        for (Pedido pedido : pedidos) {
            
            lista.addRow(new String[]{
                String.valueOf(pedido.getId()),
                pedido.getNomeCliente(),
                String.valueOf(pedido.getValorTotal()),
                String.valueOf(pedido.getQtdeItens()),
                pedido.getPedidoPosicao().name()
            });
        }
        
        jTable1.setModel(lista);
        
    }
    
    public void selecao(){
        
        int linha = jTable1.getSelectedRow();
        
        String selecaoStr = this.lista.getValueAt(linha, 0).toString();
        String selecaoPos = this.lista.getValueAt(linha, 4).toString();
        this.selecao = Integer.parseInt(selecaoStr);
        
        if(selecaoPos.equals(PedidoPosicao.ABERTO.name())){
            this.pp = PedidoPosicao.ABERTO;
        }else if(selecaoPos.equals(PedidoPosicao.LIBERADO.name())){
            this.pp = PedidoPosicao.LIBERADO;
        }else{
            this.pp = PedidoPosicao.CANCELADO;
        }
        
    }
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        montaLista();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtProcurar = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiPedidos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppaSystem - Área de Trabalho");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setTitle("Pedidos");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/appaSystem/com/auxiliar/icons/pedidos.png"))); // NOI18N
        jInternalFrame1.setVisible(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Procurar");

        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });
        txtProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProcurarKeyReleased(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appaSystem/com/auxiliar/icons/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appaSystem/com/auxiliar/icons/alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appaSystem/com/auxiliar/icons/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appaSystem/com/auxiliar/icons/atualizar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLiberar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNovo)
                            .addComponent(btnAlterar)
                            .addComponent(btnExcluir)
                            .addComponent(btnAtualizar)))
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLiberar)
                        .addComponent(btnCancelar))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastros");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jmiPedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appaSystem/com/auxiliar/icons/pedidos.png"))); // NOI18N
        jmiPedidos.setText("Pedidos");
        jmiPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiPedidosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiPedidosMousePressed(evt);
            }
        });
        jMenu1.add(jmiPedidos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        getAccessibleContext().setAccessibleDescription("Área de trabalho do sistema AppaSystem");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiPedidosMouseClicked
        
        jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_jmiPedidosMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jmiPedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiPedidosMousePressed
        
        jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_jmiPedidosMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        int resp = -999;

        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "É necessário escolher um pedido para ser Cancelado");
        }else{
            resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja cancelar o pedido número "+this.selecao+"?");
        }
        if(resp != -999){
            if(resp == JOptionPane.YES_OPTION){

                PedidoController pc = new PedidoController(this.selecao);
                pc.cancelar();

                this.selecao = 0;

                montaLista();
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed

        int resp = -999;

        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "É necessário escolher um pedido para ser Liberado");
        }else{
            resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja liberar o pedido número "+this.selecao+"?");
        }
        if(resp != -999){
            if(resp == JOptionPane.YES_OPTION){

                if(pp.equals(PedidoPosicao.LIBERADO)){
                    JOptionPane.showMessageDialog(null, "O pedido já está Liberado! É possível apenas cancelar.");
                }else if(pp.equals(PedidoPosicao.CANCELADO)){
                    JOptionPane.showMessageDialog(null, "O pedido está Cancelado!");
                }else{

                    PedidoController pc = new PedidoController(this.selecao);
                    pc.liberar();

                    this.selecao = 0;

                    montaLista();

                }
            }
        }
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int resp = -999;

        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "É necessário escolher um pedido para ser excluído");
        }else{
            resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja exluir o pedido número "+this.selecao+"?");
        }
        if(resp != -999){
            if(resp == JOptionPane.YES_OPTION){

                if(pp.equals(PedidoPosicao.LIBERADO)){
                    JOptionPane.showMessageDialog(null, "O pedido está Liberado! É possível apenas cancelar.");
                }else{

                    PedidoController pc = new PedidoController(this.selecao);
                    pc.excluir(this.selecao);

                    this.selecao = 0;

                    montaLista();

                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if(this.selecao == 0){
            JOptionPane.showMessageDialog(null, "Selecione um pedido para ser alterado!");
        }else{
            if(pp.equals(PedidoPosicao.ABERTO)){

                jdlCadastroPedido form = new jdlCadastroPedido(this, true, this.selecao, Acao.ALTERACAO);
                form.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Não é possível alterar um pedido que esteja com a posição\n"
                    + "Cancelado ou Liberado!");
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        jdlCadastroPedido form = new jdlCadastroPedido(this, true, this.selecao, Acao.INCLUSAO);
        form.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProcurarKeyReleased
        montaLista();
    }//GEN-LAST:event_txtProcurarKeyReleased

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcurarActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        selecao();
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selecao();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        montaLista();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem jmiPedidos;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
